Repository Qiskit/qiskit-addon-utils, pull requests merged in 2024-09, with the labels that each got.

#3 ci: configure mergify
  .mergify.yml
Labels: stable backport potential

#5 Update docs workflow
  .github/workflows/docs.yml
Labels: documentation, stable backport potential

#4 docs: add citation info
  CITATION.bib
  README.md
  docs/index.rst
Labels: stable backport potential

#8 ci: remove custom docs artifact name
  .github/workflows/docs.yml
Labels: stable backport potential

#21 docs: move release notes to 0.1
  releasenotes/config.yaml
  releasenotes/notes/0.1/rename-include-barriers-kwarg-838ca7f5a5e2dad6.yaml
Labels: stable backport potential

#19 ci: allow different Python versions for doctests
  .github/workflows/test_development_versions.yml
  .github/workflows/test_latest_versions.yml
  .github/workflows/test_minimum_versions.yml
  test/README.md
  tox.ini
Labels: stable backport potential

#20 ci: pin development versions to commit SHAs
  .github/workflows/test_development_versions.yml
Labels: stable backport potential

#18 Speed up tox and ci
  .github/workflows/test_development_versions.yml
  .github/workflows/test_latest_versions.yml
  .github/workflows/test_minimum_versions.yml
  tox.ini
Labels: stable backport potential, ci-cd

#27 ci: Upload to Coveralls always
  .github/workflows/coverage.yml
Labels: ci-cd

#31 ci: Build wheels first in development version tests
  .github/workflows/docs.yml
  .github/workflows/lint.yml
  .github/workflows/test_development_versions.yml
  .github/workflows/test_minimum_versions.yml
Labels: ci-cd

#30 Add a coloring how-to
  docs/how_tos/color_device_edges_to_improve_depth.ipynb
  pyproject.toml
Labels: stable backport potential

#35 Add link to Qiskit addons on landing pages
  README.md
  docs/index.rst
Labels: documentation, stable backport potential
